# Generated by Django 2.2.13 on 2021-07-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=5000)),
                ('author', models.CharField(max_length=1000)),
                ('publication_date', models.DateTimeField(editable=False, null=True)),
                ('pdf', models.FileField(upload_to='article/pdfs/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='article/banner/')),
            ],
        ),
    ]
